[theme]
# Primary accent color for interactive elements.
#primaryColor = "#d33682"
primaryColor="#0099cc"

# Background color for the main content area.
#backgroundColor = "#002b36"
backgroundColor = "#ffffff

# Background color used for the sidebar and most interactive widgets.
#secondaryBackgroundColor = "#586e75"
secondaryBackgroundColor="#ffc706"

# Color used for almost all text.
#textColor = "#fafafa"
textColor="#000000"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"